apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: digicel/auth
      context: auth
      docker:
        dockerfile: DockerFile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: digicel/transactions
      context: transactions
      docker:
        dockerfile: DockerFile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: digicel/sms
      context: sms
      docker:
        dockerfile: DockerFile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
