apiVersion: apps/v1
kind: Deployment
metadata:
  name: cash-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cash
  template:
    metadata:
      labels:
        app: cash
    spec:
      containers:
        - name: cash
          image: digicel/cash:latest
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: digicel
            - name: MONGO_URI
              value: 'mongodb://host.docker.internal:27017/digicel'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: cash-srv
spec:
  selector:
    app: cash
  ports:
    - name: cash
      protocol: TCP
      port: 3000
      targetPort: 3000
